apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    velero.io/resource-timeout: 10m0s
    velero.io/source-cluster-k8s-gitversion: v1.27.16+03a907c
    velero.io/source-cluster-k8s-major-version: '1'
    velero.io/source-cluster-k8s-minor-version: '27'
  generateName: openshift-storage-backup-
  labels:
    app: openshift-storage
    component: noobaa-db
  namespace: openshift-adp
spec:
  csiSnapshotTimeout: 10m0s
  datamover: kopia
  defaultVolumesToFsBackup: true
  hooks:
    resources:
      - includedNamespaces:
          - openshift-storage
        labelSelector:
          matchExpressions:
            - key: noobaa-db
              operator: In
              values:
                - postgres
        name: pg_dump
        pre:
          - exec:
              command:
                - rm
                - -f
                - /tmp/pg_dumpall.gz
              container: db
              onError: Continue
              timeout: 10s
          - exec:
              command:
                - /bin/bash
                - -c
                - /usr/bin/pg_dumpall -U postgres -c | /usr/bin/gzip -9 -f > /tmp/pg_dumpall.gz
              container: db
              onError: Fail
              timeout: 1800s
  includedNamespaces:
    - openshift-storage
  itemOperationTimeout: 0h5m0s
  metadata: {}
  snapshotMoveData: true
  storageLocation: ${STORAGE}
  ttl: 24h0m0s
  volumeSnapshotLocations:
    - ${STORAGE}
