apiVersion: velero.io/v1
kind: Restore
metadata:
  generateName: openshift-storage-restore-
  namespace: openshift-adp
  labels:
    app: openshift-storage
    component: noobaa-db
spec:
  excludedResources:
  - events.events.k8s.io
  - backingstores.noobaa.io
  - bucketclasses.noobaa.io
  - cephblockpoolradosnamespaces.ceph.rook.io
  - cephblockpools.ceph.rook.io
  - ephbucketnotifications.ceph.rook.io
  - cephbuckettopics.ceph.rook.io
  - cephclients.ceph.rook.io
  - cephclusters.ceph.rook.io
  - cephcosidrivers.ceph.rook.io
  - cephfilesystemmirrors.ceph.rook.io
  - cephfilesystems.ceph.rook.io
  - cephfilesystemsubvolumegroups.ceph.rook.io
  - cephnfses.ceph.rook.io
  - cephobjectrealms.ceph.rook.io
  - cephobjectstores.ceph.rook.io
  - cephobjectstoreusers.ceph.rook.io
  - cephobjectzonegroups.ceph.rook.io
  - cephobjectzones.ceph.rook.io
  - cephrbdmirrors.ceph.rook.io
  - ceph.rook.io
  - namespacestores.noobaa.io
  - noobaaaccounts.noobaa.io
  - noobaas.noobaa.io
  - objectbucketclaims.objectbucket.io
  - objectbuckets.objectbucket.io
  - storagesystem.odf.openshift.io
  - storagecluster.ocs.openshift.io
  - csiaddons.openshift.io
  - deployment.apps
  - rbac.authorization.k8s.io
  - RoleBinding
  - rolebindings
  - Role
  - roles
  - Route
  - events
  - jobs
  - Lease
  - DaemonSet
  - ControllerRevision
  - ClusterServiceVersion
  - ControllerRevision
  - Endpoints
  - EndpointSlice
  - HorizontalPodAutoscaler
  - OCSInitialization
  - OperatorCondition
  - OperatorGroup
  - ReclaimSpaceJob
  - ReplicaSet
  hooks:
    resources:
      - includedNamespaces:
          - openshift-storage
        labelSelector:
          matchExpressions:
            - values:
                - postgres
              key: noobaa-db
              operator: In
        postHooks:
          - exec:
              command:
                - "/bin/bash"
                - "-c"
                - /usr/bin/zcat /tmp/pg_dumpall.gz | /usr/bin/pg_restore -U postgres
              container: db
              execTimeout: 180s
              waitForReady: true
              onError: Fail
        name: pg_restore
  includedNamespaces:
    - openshift-storage
  backupName: ${BACKUPID}
